[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "s1setup"
version = "0.0.1"
description = "Code for Sentinel-1 preprocessing (some requires the Gamma SAR processor)"
authors = [
    { name = "Ian Joughin", email = "irj@uw.edu" }
]
license = { text = "MIT" }
readme = "README.md"
keywords = ["SAR", "Sentinel-1", "GrIMP", "Gamma"]
requires-python = ">=3.8"

dependencies = [
    "sarfunc",
    "utilities",
    "numpy",
    "pyyaml",
    "asfSearchAndDownload",
    "beautifulsoup4",
    "lxml"
]

[tool.setuptools]
packages = ["s1setup"]

[project.urls]
Homepage = "https://github.com/fastice/s1setup"
Repository = "https://github.com/fastice/s1setup"

[project.scripts]
sweepS1 = "s1setup.sweepS1:main"
"sweepS1.py" = "s1setup.sweepS1:main"
catMultipleTops = "s1setup.catMultipleTops:main"
"catMultipleTops.py" = "s1setup.catMultipleTops:main"
checkframes = "s1setup.checkframes:main"
"checkframes.py" = "s1setup.checkframes:main"
cloneSLCdir = "s1setup.cloneSLCdir:main"
"cloneSLCdir.py" = "s1setup.cloneSLCdir:main"
cullSLCclones = "s1setup.cullSLCclones:main"
"cullSLCclones.py" = "s1setup.cullSLCclones:main"
trimTopsSLCsToFit = "s1setup.trimTopsSLCsToFit:main"
"trimTopsSLCsToFit.py" = "s1setup.trimTopsSLCsToFit:main"
setupTrack = "s1setup.setupTrack:main"
"setupTrack.py" = "s1setup.setupTrack:main"
setupS1Tracks = "s1setup.setupS1Tracks:main"
"setupS1Tracks.py" = "s1setup.setupS1Tracks:main"
updateOffsetsToTiff = "s1setup.updateOffsetsToTiff:main"
"updateOffsetsToTiff.py" = "s1setup.updateOffsetsToTiff:main"
segmentTrack = "s1setup.segmentTrack:main"
"segmentTrack.py" = "s1setup.segmentTrack:main"
setupSeveralTopsImages = "s1setup.setupSeveralTopsImages:main"
"setupSeveralTopsImages.py" = "s1setup.setupSeveralTopsImages:main"
setupStrackReg = "s1setup.setupStrackReg:main"
"setupStrackReg.py" = "s1setup.setupStrackReg:main"
updateS1State = "s1setup.updateS1State:main"
"updateS1State.py" = "s1setup.updateS1State:main"
computeBurstTimes = "s1setup.computeBurstTimes:main"
"computeBurstTimes.py" = "s1setup.computeBurstTimes:main"
findgain = "s1setup.findgain:main"
"findgain.py" = "s1setup.findgain:main"
radcalcoeffs = "s1setup.radcalcoeffs:main"
"radcalcoeffs.py" = "s1setup.radcalcoeffs:main"
runPreProcTops = "s1setup.runPreProcTops:main"
"runPreProcTops.py" = "s1setup.runPreProcTops:main"
reprocessS1 = "s1setup.reprocessS1:main"
"reprocessS1.py" = "s1setup.reprocessS1:main"
dequeuePboss = "s1setup.dequeuePboss:main"
"dequeuePboss.py" = "s1setup.dequeuePboss:main"
prepareS1Pairs = "s1setup.prepareS1Pairs:main"
"prepareS1Pairs.py" = "s1setup.prepareS1Pairs:main"
setuppairs = "s1setup.setuppairs:main"
"setuppairs.py" = "s1setup.setuppairs:main"
